export const StatesArray = [
  { description: "ALABAMA", id: "AL" },
  { description: "ALASKA", id: "AK" },
  { description: "AMERICAN SAMOA", id: "AS" },
  { description: "ARIZONA", id: "AZ" },
  { description: "ARKANSAS", id: "AR" },
  { description: "CALIFORNIA", id: "CA" },
  { description: "COLORADO", id: "CO" },
  { description: "CONNECTICUT", id: "CT" },
  { description: "DELAWARE", id: "DE" },
  { description: "DISTRICT OF COLUMBIA", id: "DC" },
  { description: "FEDERATED STATES OF MICRONESIA", id: "FM" },
  { description: "FLORIDA", id: "FL" },
  { description: "GEORGIA", id: "GA" },
  { description: "GUAM", id: "GU" },
  { description: "HAWAII", id: "HI" },
  { description: "IDAHO", id: "ID" },
  { description: "ILLINOIS", id: "IL" },
  { description: "INDIANA", id: "IN" },
  { description: "IOWA", id: "IA" },
  { description: "KANSAS", id: "KS" },
  { description: "KENTUCKY", id: "KY" },
  { description: "LOUISIANA", id: "LA" },
  { description: "MAINE", id: "ME" },
  { description: "MARSHALL ISLANDS", id: "MH" },
  { description: "MARYLAND", id: "MD" },
  { description: "MASSACHUSETTS", id: "MA" },
  { description: "MICHIGAN", id: "MI" },
  { description: "MINNESOTA", id: "MN" },
  { description: "MISSISSIPPI", id: "MS" },
  { description: "MISSOURI", id: "MO" },
  { description: "MONTANA", id: "MT" },
  { description: "NEBRASKA", id: "NE" },
  { description: "NEVADA", id: "NV" },
  { description: "NEW HAMPSHIRE", id: "NH" },
  { description: "NEW JERSEY", id: "NJ" },
  { description: "NEW MEXICO", id: "NM" },
  { description: "NEW YORK", id: "NY" },
  { description: "NORTH CAROLINA", id: "NC" },
  { description: "NORTH DAKOTA", id: "ND" },
  { description: "NORTHERN MARIANA ISLANDS", id: "MP" },
  { description: "OHIO", id: "OH" },
  { description: "OKLAHOMA", id: "OK" },
  { description: "OREGON", id: "OR" },
  { description: "PALAU", id: "PW" },
  { description: "PENNSYLVANIA", id: "PA" },
  { description: "PUERTO RICO", id: "PR" },
  { description: "RHODE ISLAND", id: "RI" },
  { description: "SOUTH CAROLINA", id: "SC" },
  { description: "SOUTH DAKOTA", id: "SD" },
  { description: "TENNESSEE", id: "TN" },
  { description: "TEXAS", id: "TX" },
  { description: "UTAH", id: "UT" },
  { description: "VERMONT", id: "VT" },
  { description: "VIRGIN ISLANDS", id: "VI" },
  { description: "VIRGINIA", id: "VA" },
  { description: "WASHINGTON", id: "WA" },
  { description: "WEST VIRGINIA", id: "WV" },
  { description: "WISCONSIN", id: "WI" },
  { description: "WYOMING", id: "WY" },
]
